FROM elyra/kernel-tf-py:dev

#USER root  # switch to root user to perform installation (if necessary)

CMD ["/bin/bash", "-ec", "while :; do echo '.'; sleep 320 ; done"]

#USER jovyan  # switch back to the jovyan user 
